import { RoomAmenities, RoomDto } from "@app/rooms/common";

export const ROOMS_DTO_STUB: RoomDto[] = [
  {
    id: 1,
    building: 1,
    guests: 2,
    beds: 1,
    bathrooms: 1,
    bedrooms: 1,
    price: 2500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 2,
    building: 2,
    guests: 3,
    beds: 1,
    bathrooms: 2,
    bedrooms: 4,
    price: 7500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 3,
    building: 5,
    guests: 4,
    beds: 2,
    bathrooms: 2,
    bedrooms: 3,
    price: 8500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 4,
    building: 3,
    guests: 3,
    beds: 3,
    bathrooms: 2,
    bedrooms: 2,
    price: 4500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 5,
    building: 6,
    guests: 2,
    beds: 2,
    bathrooms: 2,
    bedrooms: 3,
    price: 2500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 6,
    building: 4,
    guests: 4,
    beds: 3,
    bathrooms: 1,
    bedrooms: 3,
    price: 5500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 7,
    building: 4,
    guests: 2,
    beds: 3,
    bathrooms: 4,
    bedrooms: 4,
    price: 10000,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 8,
    building: 3,
    guests: 3,
    beds: 3,
    bathrooms: 3,
    bedrooms: 1,
    price: 6500,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "A cozy apartment in the very center of the city. Within walking distance of NIITO, Spartak stadium, central park, railway station, metro, Lenin Square",
    photos: [
      "/assets/images/rooms/photo-22.jpeg",
      "/assets/images/rooms/photo-23.jpeg",
      "/assets/images/rooms/photo-24.jpeg",
      "/assets/images/rooms/photo-25.jpeg",
      "/assets/images/rooms/photo-26.jpeg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
];
