import { RoomAmenities, RoomDto } from "@app/rooms/common";

export const ROOMS_DTO_STUB: RoomDto[] = [
  {
    id: 1,
    building: 1,
    guests: 2,
    beds: 1,
    bathrooms: 1,
    bedrooms: 1,
    price: 120,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "Hotel Palau Fugit features a seasonal outdoor swimming pool, shared lounge, a restaurant and bar in Girona. This 4-star hotel offers a concierge service and a tour desk. The accommodation provides a 24-hour front desk, airport transfers, room service and free WiFi throughout the property.",
    photos: [
      "/assets/images/rooms/photo-01.jpg",
      "/assets/images/rooms/photo-02.jpg",
      "/assets/images/rooms/photo-03.jpg",
      "/assets/images/rooms/photo-04.jpg",
      "/assets/images/rooms/photo-05.jpg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 2,
    building: 2,
    guests: 3,
    beds: 1,
    bathrooms: 2,
    bedrooms: 4,
    price: 116,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "This family-run hotel is a 5-minute walk from Girona Cathedral. It offers a garden terrace with a small swimming pool, and rooms with flat-screen TV and free WiFi. All the elegant rooms include climate control, a safe and kettle. Apartments also have a kitchenette. Bathrobes, slippers and a professional hairdryer are provided in the modern bathrooms.",
    photos: [
      "/assets/images/rooms/photo-11.jpg",
      "/assets/images/rooms/photo-12.jpg",
      "/assets/images/rooms/photo-13.jpg",
      "/assets/images/rooms/photo-14.jpg",
      "/assets/images/rooms/photo-15.jpg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 3,
    building: 3,
    guests: 3,
    beds: 3,
    bathrooms: 2,
    bedrooms: 2,
    price: 98,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "Hotel Gran Ultonia is situated just 500 metres from Girona Cathedral and the historic Barri Vell district. Each air-conditioned room includes a rain shower, free Wi-Fi and a flat-screen TV. The stylish, functional rooms at the Gran Ultonia feature soft lighting and hardwood floors. They all have a minibar, a safe and an elegant, modern bathroom with a hairdryer and toiletries.",
    photos: [
      "/assets/images/rooms/photo-21.jpg",
      "/assets/images/rooms/photo-22.jpg",
      "/assets/images/rooms/photo-23.jpg",
      "/assets/images/rooms/photo-24.jpg",
      "/assets/images/rooms/photo-25.jpg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 4,
    building: 4,
    guests: 4,
    beds: 3,
    bathrooms: 1,
    bedrooms: 3,
    price: 92,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "With 150 years of experience as a hotel in Girona, we know that our guests value enjoying an excellent relaxing experience above everything else, along with services of the highest quality and the support of a professional and attentive team of professionals. For this reason, all of the members of our team share the same philosophy and commitment: ensuring that guests have fond memories of their stay in our hotel. We love it when they come back!",
    photos: [
      "/assets/images/rooms/photo-31.jpeg",
      "/assets/images/rooms/photo-32.jpg",
      "/assets/images/rooms/photo-33.jpg",
      "/assets/images/rooms/photo-34.jpg",
      "/assets/images/rooms/photo-35.jpg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
  {
    id: 5,
    building: 3,
    guests: 3,
    beds: 3,
    bathrooms: 3,
    bedrooms: 1,
    price: 162,
    amenities: [
      RoomAmenities.TV,
      RoomAmenities.ELEVATOR,
      RoomAmenities.CARBON_MONOXIDE_ALARM,
      RoomAmenities.HEATING,
      RoomAmenities.AIR_CONDITIONING,
    ],
    description:
      "Housed in a restored 18th-century building, Hotel Museu Llegendes de Girona is located in Girona's old town, 150 metres from the Cathedral and Arab Baths. Rooms feature flat-screen TV, rain showers and free Wi-Fi. This design hotel offers elegant, individually decorated rooms. They all include air conditioning, a safe and minibar. The stylish modern bathrooms come with toiletries and slippers. Some have bathrobes.",
    photos: [
      "/assets/images/rooms/photo-41.jpg",
      "/assets/images/rooms/photo-42.jpg",
      "/assets/images/rooms/photo-43.jpg",
      "/assets/images/rooms/photo-44.jpg",
      "/assets/images/rooms/photo-45.jpg",
    ],
    created: "2023-09-11T00:00:00.000Z",
    updated: "2023-09-11T00:00:00.000Z",
  },
];
